const routine = [
 {name:'Wake Up & Come Online',tasks:[{id:'water',title:'Drink a glass of water',detail:'A small first step.',minutes:1},{id:'light',title:'Open the curtains',detail:'Let a little daylight in.',minutes:1},{id:'stretch',title:'Stretch & take a breath',detail:'Ease into your body.',minutes:5,quick:1},{id:'journal',title:'Write a few thoughts',detail:'Whatever is on your mind.',minutes:5,optional:true}]},
 {name:'Get Ready',tasks:[{id:'wash',title:'Wash & freshen up',detail:'Take care of the basics.',minutes:10,quick:3},{id:'teeth',title:'Brush your teeth',detail:'A little care for yourself.',minutes:2},{id:'dress',title:'Get dressed',detail:'Something comfortable for today.',minutes:5},{id:'tidy',title:'Make the bed',detail:'A small moment of order.',minutes:2,optional:true}]},
 {name:'Start the Day',tasks:[{id:'breakfast',title:'Have some breakfast',quickTitle:'Grab a simple breakfast',detail:'Give yourself some fuel.',minutes:15,quick:5},{id:'plan',title:'Choose today’s priorities',quickTitle:'Choose one priority',detail:'One useful next step is enough.',minutes:5,quick:1},{id:'essentials',title:'Gather your essentials',detail:'Phone, keys, bag — whatever you need.',minutes:2},{id:'pause',title:'Enjoy a quiet cup',detail:'A little time just for you.',minutes:10,optional:true}]}
];
const key='soft-morning-v1';let state={mode:'normal',done:[],started:new Date().toISOString()};let storageAvailable=true;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved && ['normal','emergency'].includes(saved.mode)&&Array.isArray(saved.done)){state={...state,...saved,done:saved.done.filter(id=>typeof id==='string')}}}catch(e){storageAvailable=false}
const $=id=>document.getElementById(id);
function save(){try{localStorage.setItem(key,JSON.stringify(state));storageAvailable=true}catch(e){storageAvailable=false}$('saved').textContent=storageAvailable?'Your progress is saved on this device.':'Progress is only saved while this page stays open.';$('status').textContent=storageAvailable?'':'Your browser could not save progress. Try a regular Safari tab with website storage enabled.'}
function visibleTasks(section){return section.tasks.filter(t=>state.mode==='normal'||!t.optional)}
function minutes(task){return state.mode==='emergency'?(task.quick??task.minutes):task.minutes}
function render(){const emergency=state.mode==='emergency';$('normal').setAttribute('aria-pressed',!emergency);$('emergency').setAttribute('aria-pressed',emergency);const tasks=routine.flatMap(visibleTasks);const completed=tasks.filter(t=>state.done.includes(t.id)).length;const percent=Math.round(completed/tasks.length*100);$('modeNote').textContent=emergency?'Just the essentials. Optional tasks are tucked away; longer activities are shortened.':'Take your time. Optional tasks are included, with space for a gentler start.';$('percent').textContent=percent+'%';$('bar').value=percent;$('count').textContent=`${completed} of ${tasks.length} tasks complete · about ${tasks.filter(t=>!state.done.includes(t.id)).reduce((n,t)=>n+minutes(t),0)} min remaining`;$('encouragement').textContent=completed===tasks.length?'You’re ready for the day.':completed===0?'One small step at a time.':'You’re finding your rhythm.';
 $('sections').replaceChildren(...routine.map((section,i)=>{const el=document.createElement('section');const shown=visibleTasks(section);el.innerHTML=`<div class="step">Chapter 0${i+1}</div><header><h2>${section.name.replace('&','&amp;')}</h2><span>${shown.filter(t=>state.done.includes(t.id)).length} / ${shown.length}</span></header><div class="tasks"></div>`;shown.forEach(task=>{const label=document.createElement('label');const check=document.createElement('input');check.type='checkbox';check.checked=state.done.includes(task.id);check.setAttribute('aria-label',emergency&&task.quickTitle?task.quickTitle:task.title);check.addEventListener('change',()=>{state.done=check.checked?[...new Set([...state.done,task.id])]:state.done.filter(id=>id!==task.id);save();updateProgress()});const text=document.createElement('span');text.className='tasktext';text.innerHTML=`<span class="title">${emergency&&task.quickTitle?task.quickTitle:task.title}</span>${task.optional?'<span class="optional">Optional</span>':''}<span class="details">${task.detail}</span>`;const time=document.createElement('span');time.className='duration';time.textContent=minutes(task)+' min';label.append(check,text,time);el.querySelector('.tasks').append(label)});return el}));}
function updateProgress(){const tasks=routine.flatMap(visibleTasks);const n=tasks.filter(t=>state.done.includes(t.id)).length;const percent=Math.round(n/tasks.length*100);$('percent').textContent=percent+'%';$('bar').value=percent;$('count').textContent=`${n} of ${tasks.length} tasks complete · about ${tasks.filter(t=>!state.done.includes(t.id)).reduce((sum,t)=>sum+minutes(t),0)} min remaining`;$('encouragement').textContent=n===tasks.length?'You’re ready for the day.':n===0?'One small step at a time.':'You’re finding your rhythm.';document.querySelectorAll('section header span').forEach((el,i)=>{const t=visibleTasks(routine[i]);el.textContent=`${t.filter(t=>state.done.includes(t.id)).length} / ${t.length}`})}
['normal','emergency'].forEach(mode=>$(mode).addEventListener('click',()=>{state.mode=mode;save();render()}));$('reset').addEventListener('click',()=>$('confirm').showModal());$('cancel').addEventListener('click',()=>$('confirm').close());$('clear').addEventListener('click',()=>{state.done=[];state.started=new Date().toISOString();save();render();$('confirm').close();$('reset').focus();$('status').textContent='A fresh start. Your checkmarks have been cleared.'});$('date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});render();save();

// Keep the original storage key and task IDs so routine updates retain progress.
if ('serviceWorker' in navigator && /^https?:$/.test(location.protocol)) {
  navigator.serviceWorker.register('./sw.js', {scope:'./'}).then(async registration => {
    await navigator.serviceWorker.ready;
    $('offlineStatus').textContent = 'Ready to use offline. Open from your Home Screen for daily use.';
    if (registration.waiting) $('offlineStatus').textContent = 'An update is ready. Close all Cozy Morning windows and reopen to use it.';
    registration.addEventListener('updatefound', () => {
      const worker = registration.installing;
      worker.addEventListener('statechange', () => {
        if(worker.state === 'installed' && navigator.serviceWorker.controller) $('offlineStatus').textContent = 'An update is ready. Close all Cozy Morning windows and reopen to use it.';
      });
    });
  }).catch(() => { $('offlineStatus').textContent = 'Offline setup did not finish. Reopen while connected to the internet to try again.'; });
} else {
  $('offlineStatus').textContent = 'Offline installation is available when opened from the published website.';
}
